<?php

/**
 * @file
 * Contains debug_log.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use \Drupal\views\ViewExecutable;
use Drupal\views\Plugin\views\query\QueryPluginBase;

/**
 * Implements hook_help().
 */
function debug_log_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the debug_log module.
    case 'help.page.debug_log':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('debug and return it in file') . '</p>';
      return $output;

    default:
  }
}


function debug_log_views_query_alter(ViewExecutable $view, QueryPluginBase $query) {
	//dump('debug_log');
}
